In [1]:
import pandas as pd
import math

In [7]:
data = pd.read_csv('Data/2017_season_efficiencies.csv')
data

      TEAM     OPASS     ORUSH      OINT      DPASS     DRUSH      TPEN
0      AFA  6.933948  4.405029  0.072675   8.611795  6.212274  0.511134
1      AKR  5.302789  2.845550  0.026530   7.480557  5.332432  0.883592
2      ALA  6.779588  5.574854  0.008398   5.506383  2.601949  0.647997
3      APP  7.140901  5.293620  0.020901   7.192958  3.859408  0.892332
4     ARIZ  8.392635  6.195761  0.047879   7.969529  4.255996  0.738341
5      ARK  6.233027  4.148516  0.022707   8.957885  4.971080  0.686531
6     ARMY  8.215539  5.674099  0.098479   6.929083  5.813491  0.546738
7     ARST  7.345851  3.923012  0.038542   7.234272  3.428018  0.887972
8      ASU  6.750188  3.791517  0.023661   7.591953  4.783801  0.521295
9      AUB  7.593955  4.774347  0.012306   5.845576  3.667079  0.495023
10    BALL  4.347525  3.518993  0.032531   9.435791  5.012117  0.530666
11     BAY  6.118121  2.994056  0.030213   8.626158  5.002313  0.805460
12      BC  5.624709  4.542985  0.027962   6.182343  4.660209  0.395556
13    BGSU  6.103883  3.988998  0.032783   7.989918  5.675029  0.889701
14     BSU  7.452192  3.739792  0.014612   6.419428  3.254103  0.730261
15    BUFF  8.143038  3.585107  0.017171   7.300511  4.281114  0.712746
16     BYU  5.226928  3.529662  0.048721   8.312924  3.544835  0.594684
17     CAL  5.640249  3.105078  0.024126   7.857200  3.888310  0.750165
18    CCAR  6.411208  3.948222  0.029381   7.736741  4.166990  1.033570
19    CHAR  4.461834  4.372420  0.048024   7.986437  4.806320  1.055447
20     CIN  5.594582  4.375971  0.022594   9.484825  4.327578  1.094865
21    CLEM  5.757354  4.493579  0.020222   5.007378  3.158176  0.615858
22     CMU  6.961932  3.573074  0.033989   6.031866  4.288509  0.878065
23    COLO  6.194884  3.576645  0.021288   7.588427  5.201101  0.665869
24    CONN  6.820027  3.533319  0.029646   8.518219  5.046137  0.665606
25     CSU  8.281961  4.920814  0.020071   8.426358  5.184135  0.742448
26    DUKE  4.939863  3.869200  0.026820  10.183412  3.817306  0.550918
27     ECU  6.932342  3.211270  0.025221  10.970102  5.523292  0.767522
28     EMU  6.843331  3.514227  0.033939   6.411771  4.243821  0.817215
29     FAU  8.059321  5.664689  0.017093   6.951763  3.861498  0.711668
..     ...       ...       ...       ...        ...       ...       ...
100   UCLA  7.495055  3.850877  0.016960   7.352827  5.731864  1.056497
101    UGA  8.410620  5.816122  0.036325   5.696673  3.670149  0.893733
102     UK  6.196891  4.129230  0.018910   7.954322  4.580667  0.770897
103    ULL  6.029430  4.956831  0.033402   8.731278  4.954785  0.618112
104    ULM  7.728014  4.349340  0.022118   9.314356  5.562576  0.607721
105  UMASS  6.689593  3.954298  0.014853   6.979959  4.712347  0.748952
106    UMD  5.152152  3.906358  0.028892   6.711748  4.653558  1.050842
107    UNC  5.252366  3.538813  0.048205   7.419774  4.632013  1.123415
108   UNLV  6.456342  5.120316  0.032643   7.223199  5.246647  0.523886
109    UNM  5.094841  4.926609  0.072308   8.223237  4.785856  0.804661
110    UNT  6.847929  3.939014  0.028970   7.956335  4.675936  0.656976
111    USA  5.671625  2.808695  0.035609   8.204301  3.942987  0.806663
112    USC  7.992155  4.658695  0.027821   6.916926  4.224129  0.967823
113    USF  7.368281  5.195067  0.014353   6.700439  3.360069  1.093726
114    USM  6.799492  4.846235  0.016566   6.801191  3.649128  0.967244
115    USU  5.923361  4.425034  0.029242   6.292657  4.508425  0.830482
116   UTAH  6.672376  3.794104  0.029980   6.246345  3.822873  0.758452
117   UTEP  4.161782  3.082639  0.040719   7.731395  5.350421  0.925790
118   UTSA  5.721194  4.529440  0.020862   7.158606  3.823913  0.834540
119    UVA  5.707006  2.961152  0.022716   6.359535  4.509639  0.700914
120    VAN  6.659670  3.354048  0.022146   7.751382  4.670836  0.801186
121     VT  6.889339  3.823686  0.022246   7.840570  3.299535  0.571531
122   WAKE  7.773125  4.347685  0.014773   6.679597  4.216667  0.592371
123   WASH  7.399711  4.737057  0.017750   6.045771  2.562783  0.539401
124    WIS  7.637204  4.850720  0.050793   5.777253  3.102007  0.748494
125    WKU  6.357368  1.775323  0.018806   6.855947  4.537496  0.718557
126    WMU  5.562987  4.405003  0.027640   7.303664  4.330881  0.677358
127    WSU  5.776408  2.436454  0.028801   6.846048  4.209150  0.682879
128    WVU  7.813716  3.847344  0.028013   8.033600  5.056936  0.844533
129    WYO  5.381190  3.249128  0.021264   6.937551  3.363671  0.661525

[130 rows x 7 columns]

In [3]:
#NOT Scaled
def logit_team(stat_list):
    '''
    Order of stat list items: [OPASS, ORUSH, OINT, DPASS, DRUSH, TPEN]
    '''
    
    logit = (
        (0.55*stat_list[0]) +
        (0.52*stat_list[1]) -
        (9.53*stat_list[2]) -
        (0.54*stat_list[3]) -
        (0.58*stat_list[4]) -
        (0.59*stat_list[5])
    )
    return logit

In [20]:
#Scaled
def logit_team_scale(stat_list):
    '''
    Order of stat list items: [OPASS, ORUSH, OINT, DPASS, DRUSH, TPEN]
    '''
    
    logit = (
        (1.41*stat_list[0]) +
        (0.92*stat_list[1]) -
        (0.64*stat_list[2]) -
        (1.44*stat_list[3]) -
        (1.06*stat_list[4]) -
        (0.24*stat_list[5])
    )
    return logit

In [9]:
test = data.iloc[1].tolist()
del test[0]
test

[5.302788671570365,
 2.8455499737431205,
 0.026530481013239637,
 7.480557364711123,
 5.332431846723097,
 0.8835923062983986]

In [12]:
logit_team(1, test)

-3.260246637105508

In [12]:
ucf = data.iloc[99].tolist()
del ucf[0]

auburn = data.iloc[9].tolist()
del auburn[0]

In [13]:
ucf

[9.894531220848098,
 5.298234635734636,
 0.02099625285109156,
 7.406272235090152,
 4.254544396387617,
 0.9546790109123952]

In [21]:
logit_ucf = logit_team(ucf)
logit_aub = logit_team(auburn)

print(logit_ucf)
print(logit_aub)
print('------SCALED-------')

logit_ucf_s = logit_team_scale(ucf)
logit_aub_s = logit_team_scale(auburn)

print(logit_ucf_s)
print(logit_aub_s)

0.9666965190857499
0.9664827520371267
------SCALED-------
3.4082552431273143
2.668462020891308

In [22]:
logit_game = 1.24 + 0.25*0 + logit_ucf - logit_aub
print(f'Not scaled: {logit_game}')
      
logit_game_s = -0.03 + 0.13*0 + logit_ucf_s - logit_aub_s
print(f'Scaled: {logit_game_s}')

Not scaled: 1.240213767048623
Scaled: 0.7097932222360064

In [24]:
odds = math.exp(logit_game)
odds_s = math.exp(logit_game_s)

print(f'Not scaled: {odds}')
print(f'Scaled: {odds_s}')

Not scaled: 3.456352240014309
Scaled: 2.0335707179630345

In [25]:
prob = odds/(1+odds)
prob_s = odds_s/(1+odds_s)

print(f'Not scaled UCF win prob: {prob}')
print(f'Scaled UCF win prob: {prob_s}')

Not scaled UCF win prob: 0.7756012213260796
Scaled UCF win prob: 0.6703554678720414

In [26]:
print(1-prob)
print(1-prob_s)

0.22439877867392044
0.32964453212795863

## Calculate logit for every team

In [27]:
data = data.set_index('TEAM')

In [28]:
data.head()

         OPASS     ORUSH      OINT     DPASS     DRUSH      TPEN
TEAM
AFA   6.933948  4.405029  0.072675  8.611795  6.212274  0.511134
AKR   5.302789  2.845550  0.026530  7.480557  5.332432  0.883592
ALA   6.779588  5.574854  0.008398  5.506383  2.601949  0.647997
APP   7.140901  5.293620  0.020901  7.192958  3.859408  0.892332
ARIZ  8.392635  6.195761  0.047879  7.969529  4.255996  0.738341

In [29]:
team_logit = []

for index, row in data.iterrows():
    stats = row.tolist()
    team_logit.append(logit_team_scale(stats))

In [30]:
data['LOGIT'] = team_logit
data = data.reset_index()
data.head()

   TEAM     OPASS     ORUSH      OINT     DPASS     DRUSH      TPEN     LOGIT
0   AFA  6.933948  4.405029  0.072675  8.611795  6.212274  0.511134 -5.325687
1   AKR  5.302789  2.845550  0.026530  7.480557  5.332432  0.883592 -6.558584
2   ALA  6.779588  5.574854  0.008398  5.506383  2.601949  0.647997  3.839934
3   APP  7.140901  5.293620  0.020901  7.192958  3.859408  0.892332  0.262432
4  ARIZ  8.392635  6.195761  0.047879  7.969529  4.255996  0.738341  1.338393

In [31]:
output = data[['TEAM','LOGIT']]
output.head()

   TEAM     LOGIT
0   AFA -5.325687
1   AKR -6.558584
2   ALA  3.839934
3   APP  0.262432
4  ARIZ  1.338393

In [32]:
output.to_csv('Data/team_logits.csv', index=False)