In [1]:
import pandas as pd

In [66]:
df = pd.read_csv('Data/test/2017_games.csv', parse_dates=[0])

In [67]:
df.head()

,Date,Team_ID,Team,Team_Abbr,Opponent,Opp_Abbr,Result,Off Pass Att,Off Pass Yards,Off Int,...,Off Rush Yards,Def Pass Att,Def Pass Yards,Def Rush Att,Def Rush Yards,Def Sacks,Def Sack Yards,Off Plays,Pen,Pen Yards
0,2017-09-02,721,Air Force,AFA,FCS,FCS,W 62-0,14,190,0,...,473,19,40,28,55,1,16,81,5,53
1,2017-09-16,721,Air Force,AFA,Michigan,MICH,L 13-29,9,64,1,...,168,23,169,42,190,2,11,58,3,29
2,2017-09-23,721,Air Force,AFA,San Diego St.,SDSU,L 24-28,6,33,1,...,220,16,180,41,187,1,10,66,5,52
3,2017-09-30,721,Air Force,AFA,New Mexico,UNM,L 38-56,18,158,0,...,238,9,146,41,363,0,0,81,2,15
4,2017-10-07,721,Air Force,AFA,Navy,NAVY,L 45-48,17,281,0,...,340,12,86,57,471,0,0,72,3,25

In [68]:
# Drop all games with FCS opponent

df = df.drop(df[df.Opp_Abbr == 'FCS'].index).reset_index(drop=True)
df.head()

,Date,Team_ID,Team,Team_Abbr,Opponent,Opp_Abbr,Result,Off Pass Att,Off Pass Yards,Off Int,...,Off Rush Yards,Def Pass Att,Def Pass Yards,Def Rush Att,Def Rush Yards,Def Sacks,Def Sack Yards,Off Plays,Pen,Pen Yards
0,2017-09-16,721,Air Force,AFA,Michigan,MICH,L 13-29,9,64,1,...,168,23,169,42,190,2,11,58,3,29
1,2017-09-23,721,Air Force,AFA,San Diego St.,SDSU,L 24-28,6,33,1,...,220,16,180,41,187,1,10,66,5,52
2,2017-09-30,721,Air Force,AFA,New Mexico,UNM,L 38-56,18,158,0,...,238,9,146,41,363,0,0,81,2,15
3,2017-10-07,721,Air Force,AFA,Navy,NAVY,L 45-48,17,281,0,...,340,12,86,57,471,0,0,72,3,25
4,2017-10-14,721,Air Force,AFA,UNLV,UNLV,W 34-30,8,72,0,...,401,27,145,39,266,1,7,86,5,56

In [69]:
# Match oppoenent's sacks and sack yardage to each team & game (sacks against)

sack_list = []
yard_list = []

for index, row in df.iterrows():
    try:
        date = row.Date
        opp = row.Opp_Abbr
        
        sacks = df.loc[(df['Date'] == date) & (df['Team_Abbr'] == opp), 'Def Sacks'].values[0]
        sack_list.append(sacks)
        
        yards = df.loc[(df['Date'] == date) & (df['Team_Abbr'] == opp), 'Def Sack Yards'].values[0]
        yard_list.append(yards)
        
        print(index)
        
    except IndexError:
        sacks.append('none')
        sack_yards.append('none')
        print(f'{index} : IndexError')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551

In [70]:
print(f'Dataframe length: {len(df)}')
print(f'sack_list length: {len(sack_list)}')
print(f'yard_list length: {len(yard_list)}')

Dataframe length: 1552
sack_list length: 1552
yard_list length: 1552

In [71]:
# Add sacks and sack yards to dataframe

df['Off Sacks'] = sack_list
df['Off Sack Yds'] = yard_list

In [72]:
df.tail()

,Date,Team_ID,Team,Team_Abbr,Opponent,Opp_Abbr,Result,Off Pass Att,Off Pass Yards,Off Int,...,Def Pass Yards,Def Rush Att,Def Rush Yards,Def Sacks,Def Sack Yards,Off Plays,Pen,Pen Yards,Off Sacks,Off Sack Yds
1547,2017-11-04,811,Wyoming,WYO,Colorado St.,CSU,W 16-13,20,138,0,...,110,55,235,2,6,54,1,5,1,8
1548,2017-11-11,811,Wyoming,WYO,Air Force,AFA,W 28-14,15,129,0,...,175,61,203,2,12,58,5,50,3,26
1549,2017-11-18,811,Wyoming,WYO,Fresno St.,FRES,L 7-13,33,231,0,...,186,45,147,1,6,61,3,15,1,6
1550,2017-11-25,811,Wyoming,WYO,San Jose St.,SJSU,L 17-20,38,170,2,...,174,43,146,2,15,81,4,35,2,8
1551,2017-12-22,811,Wyoming,WYO,Central Mich.,CMU,W 37-14,19,154,0,...,346,27,18,5,35,61,5,49,3,18

In [73]:
# Split Result column into win/loss outcome and score

df[['Result','Score']] = df['Result'].str.split(' ', expand=True)
df.head()

,Date,Team_ID,Team,Team_Abbr,Opponent,Opp_Abbr,Result,Off Pass Att,Off Pass Yards,Off Int,...,Def Rush Att,Def Rush Yards,Def Sacks,Def Sack Yards,Off Plays,Pen,Pen Yards,Off Sacks,Off Sack Yds,Score
0,2017-09-16,721,Air Force,AFA,Michigan,MICH,L,9,64,1,...,42,190,2,11,58,3,29,3,27,13-29
1,2017-09-23,721,Air Force,AFA,San Diego St.,SDSU,L,6,33,1,...,41,187,1,10,66,5,52,0,0,24-28
2,2017-09-30,721,Air Force,AFA,New Mexico,UNM,L,18,158,0,...,41,363,0,0,81,2,15,4,29,38-56
3,2017-10-07,721,Air Force,AFA,Navy,NAVY,L,17,281,0,...,57,471,0,0,72,3,25,2,17,45-48
4,2017-10-14,721,Air Force,AFA,UNLV,UNLV,W,8,72,0,...,39,266,1,7,86,5,56,0,0,34-30

In [74]:
# Convert home field to binary

locations = df['Location'].tolist()
advantage = []

for site in locations:
    if site == 'home':
        advantage.append(1)
    elif site == 'away':
        advantage.append(0)
    elif site == 'neutral':
        advantage.append(0)

df['Home Adv'] = advantage

In [75]:
df.head(10)

,Date,Team_ID,Team,Team_Abbr,Opponent,Opp_Abbr,Result,Off Pass Att,Off Pass Yards,Off Int,...,Def Rush Yards,Def Sacks,Def Sack Yards,Off Plays,Pen,Pen Yards,Off Sacks,Off Sack Yds,Score,Home Adv
0,2017-09-16,721,Air Force,AFA,Michigan,MICH,L,9,64,1,...,190,2,11,58,3,29,3,27,13-29,0
1,2017-09-23,721,Air Force,AFA,San Diego St.,SDSU,L,6,33,1,...,187,1,10,66,5,52,0,0,24-28,1
2,2017-09-30,721,Air Force,AFA,New Mexico,UNM,L,18,158,0,...,363,0,0,81,2,15,4,29,38-56,0
3,2017-10-07,721,Air Force,AFA,Navy,NAVY,L,17,281,0,...,471,0,0,72,3,25,2,17,45-48,0
4,2017-10-14,721,Air Force,AFA,UNLV,UNLV,W,8,72,0,...,266,1,7,86,5,56,0,0,34-30,1
5,2017-10-20,721,Air Force,AFA,Nevada,NEV,W,7,41,1,...,157,0,0,98,5,58,2,7,45-42,0
6,2017-10-28,721,Air Force,AFA,Colorado St.,CSU,W,4,64,1,...,166,1,7,78,4,28,0,0,45-28,0
7,2017-11-04,721,Air Force,AFA,Army,ARMY,L,13,95,0,...,392,0,0,47,3,21,3,26,0-21,1
8,2017-11-11,721,Air Force,AFA,Wyoming,WYO,L,22,175,1,...,100,3,26,83,5,55,2,12,14-28,1
9,2017-11-18,721,Air Force,AFA,Boise St.,BSU,L,13,115,0,...,90,0,0,64,6,63,4,20,19-44,0

In [76]:
df.to_csv('Data/testing_data.csv', index=False)

In [77]:
df1 = df

In [78]:
# Create efficiency stat functions

def off_pass(pass_yds, pass_att, sack_yds, sack_tot):
    try:
        n = pass_yds - sack_yds
        d = pass_att + sack_tot
        result = n/d
        return result
    except ZeroDivisionError:
        return 0

    
def off_rush(rush_yds, rush_att):
    try:
        result = rush_yds/rush_att
        return(result)
    except ZeroDivisionError:
        return 0
    

def off_int(int_tot, pass_att):
    try:
        result = int_tot/pass_att
        return result
    except ZeroDivisionError:
        return 0
    

def def_pass(pass_yds, pass_att):
    try:
        result = pass_yds/pass_att
        return result
    except ZeroDivisionError:
        return 0
    

def def_rush(rush_yds, rush_att):
    try:
        result = rush_yds/rush_att
        return result
    except ZeroDivisionError:
        return 0
    

def team_pen(pen_yds, play_tot):
    try:
        result = pen_yds/play_tot
        return result
    except ZeroDivisionError:
        return 0

In [79]:
# Calculate efficiency stats
OPASS_list = []
ORUSH_list = []
OINT_list = []
DPASS_list = []
DRUSH_list = []
TPEN_list = []

for index, row in df1.iterrows():
    OPASS_list.append(off_pass(
        row['Off Pass Yards'],
        row['Off Pass Att'],
        row['Off Sack Yds'],
        row['Off Sacks']
    ))
    ORUSH_list.append(off_rush(row['Off Rush Yards'], row['Off Rush Att']))
    OINT_list.append(off_int(row['Off Int'], row['Off Pass Att']))
    DPASS_list.append(def_pass(row['Def Pass Yards'], row['Def Pass Att']))
    DRUSH_list.append(def_rush(row['Def Rush Yards'], row['Def Rush Att']))
    TPEN_list.append(team_pen(row['Pen Yards'], row['Off Plays']))
    print(index)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551

In [80]:
print(len(OPASS_list))
print(len(ORUSH_list))
print(len(OINT_list))
print(len(DPASS_list))
print(len(DRUSH_list))
print(len(TPEN_list))

1552
1552
1552
1552
1552
1552

In [81]:
df1['OPASS'] = OPASS_list
df1['ORUSH'] = ORUSH_list
df1['OINT'] = OINT_list
df1['DPASS'] = DPASS_list
df1['DRUSH'] = DRUSH_list
df1['TPEN'] = TPEN_list

In [82]:
df1.head()

,Date,Team_ID,Team,Team_Abbr,Opponent,Opp_Abbr,Result,Off Pass Att,Off Pass Yards,Off Int,...,Off Sacks,Off Sack Yds,Score,Home Adv,OPASS,ORUSH,OINT,DPASS,DRUSH,TPEN
0,2017-09-16,721,Air Force,AFA,Michigan,MICH,L,9,64,1,...,3,27,13-29,0,3.083333,3.428571,0.111111,7.347826,4.523810,0.500000
1,2017-09-23,721,Air Force,AFA,San Diego St.,SDSU,L,6,33,1,...,0,0,24-28,1,5.500000,3.666667,0.166667,11.250000,4.560976,0.787879
2,2017-09-30,721,Air Force,AFA,New Mexico,UNM,L,18,158,0,...,4,29,38-56,0,5.863636,3.777778,0.000000,16.222222,8.853659,0.185185
3,2017-10-07,721,Air Force,AFA,Navy,NAVY,L,17,281,0,...,2,17,45-48,0,13.894737,6.181818,0.000000,7.166667,8.263158,0.347222
4,2017-10-14,721,Air Force,AFA,UNLV,UNLV,W,8,72,0,...,0,0,34-30,1,9.000000,5.141026,0.000000,5.370370,6.820513,0.651163

In [83]:
df1.to_csv('Data/testing_data_with_efficiency.csv', index=False)

In [84]:
eff_df = df1[['Result','Home Adv','OPASS','ORUSH','OINT','DPASS','DRUSH','TPEN']]
eff_df.head()

,Result,Home Adv,OPASS,ORUSH,OINT,DPASS,DRUSH,TPEN
0,L,0,3.083333,3.428571,0.111111,7.347826,4.523810,0.500000
1,L,1,5.500000,3.666667,0.166667,11.250000,4.560976,0.787879
2,L,0,5.863636,3.777778,0.000000,16.222222,8.853659,0.185185
3,L,0,13.894737,6.181818,0.000000,7.166667,8.263158,0.347222
4,W,1,9.000000,5.141026,0.000000,5.370370,6.820513,0.651163

In [85]:
eff_df = eff_df.rename(columns={'Result':'LABEL', 'Home Adv':'HOME'})
eff_df.head()

  LABEL  HOME      OPASS     ORUSH      OINT      DPASS     DRUSH      TPEN
0     L     0   3.083333  3.428571  0.111111   7.347826  4.523810  0.500000
1     L     1   5.500000  3.666667  0.166667  11.250000  4.560976  0.787879
2     L     0   5.863636  3.777778  0.000000  16.222222  8.853659  0.185185
3     L     0  13.894737  6.181818  0.000000   7.166667  8.263158  0.347222
4     W     1   9.000000  5.141026  0.000000   5.370370  6.820513  0.651163

In [86]:
eff_df.to_csv('Data/efficiency_stats_test.csv', index=False)

# Create Production Data

The below code is using 2017 stats to create season avg efficiency stats for each team.

In [9]:
prod_df = pd.read_csv('Data/testing_data_with_efficiency.csv', parse_dates=[0])
prod_df.head()

,Date,Team_ID,Team,Team_Abbr,Opponent,Opp_Abbr,Result,Off Pass Att,Off Pass Yards,Off Int,...,Off Sacks,Off Sack Yds,Score,Home Adv,OPASS,ORUSH,OINT,DPASS,DRUSH,TPEN
0,2017-09-16,721,Air Force,AFA,Michigan,MICH,L,9,64,1,...,3,27,13-29,0,3.083333,3.428571,0.111111,7.347826,4.523810,0.500000
1,2017-09-23,721,Air Force,AFA,San Diego St.,SDSU,L,6,33,1,...,0,0,24-28,1,5.500000,3.666667,0.166667,11.250000,4.560976,0.787879
2,2017-09-30,721,Air Force,AFA,New Mexico,UNM,L,18,158,0,...,4,29,38-56,0,5.863636,3.777778,0.000000,16.222222,8.853659,0.185185
3,2017-10-07,721,Air Force,AFA,Navy,NAVY,L,17,281,0,...,2,17,45-48,0,13.894737,6.181818,0.000000,7.166667,8.263158,0.347222
4,2017-10-14,721,Air Force,AFA,UNLV,UNLV,W,8,72,0,...,0,0,34-30,1,9.000000,5.141026,0.000000,5.370370,6.820513,0.651163

In [10]:
prod_df = prod_df[['Team_Abbr','OPASS','ORUSH','OINT','DPASS','DRUSH','TPEN']]

In [11]:
prod_df = prod_df.groupby('Team_Abbr').mean().reset_index()
prod_df = prod_df.rename(columns={'Team_Abbr':'TEAM'})
prod_df

      TEAM     OPASS     ORUSH      OINT      DPASS     DRUSH      TPEN
0      AFA  6.933948  4.405029  0.072675   8.611795  6.212274  0.511134
1      AKR  5.302789  2.845550  0.026530   7.480557  5.332432  0.883592
2      ALA  6.779588  5.574854  0.008398   5.506383  2.601949  0.647997
3      APP  7.140901  5.293620  0.020901   7.192958  3.859408  0.892332
4     ARIZ  8.392635  6.195761  0.047879   7.969529  4.255996  0.738341
5      ARK  6.233027  4.148516  0.022707   8.957885  4.971080  0.686531
6     ARMY  8.215539  5.674099  0.098479   6.929083  5.813491  0.546738
7     ARST  7.345851  3.923012  0.038542   7.234272  3.428018  0.887972
8      ASU  6.750188  3.791517  0.023661   7.591953  4.783801  0.521295
9      AUB  7.593955  4.774347  0.012306   5.845576  3.667079  0.495023
10    BALL  4.347525  3.518993  0.032531   9.435791  5.012117  0.530666
11     BAY  6.118121  2.994056  0.030213   8.626158  5.002313  0.805460
12      BC  5.624709  4.542985  0.027962   6.182343  4.660209  0.395556
13    BGSU  6.103883  3.988998  0.032783   7.989918  5.675029  0.889701
14     BSU  7.452192  3.739792  0.014612   6.419428  3.254103  0.730261
15    BUFF  8.143038  3.585107  0.017171   7.300511  4.281114  0.712746
16     BYU  5.226928  3.529662  0.048721   8.312924  3.544835  0.594684
17     CAL  5.640249  3.105078  0.024126   7.857200  3.888310  0.750165
18    CCAR  6.411208  3.948222  0.029381   7.736741  4.166990  1.033570
19    CHAR  4.461834  4.372420  0.048024   7.986437  4.806320  1.055447
20     CIN  5.594582  4.375971  0.022594   9.484825  4.327578  1.094865
21    CLEM  5.757354  4.493579  0.020222   5.007378  3.158176  0.615858
22     CMU  6.961932  3.573074  0.033989   6.031866  4.288509  0.878065
23    COLO  6.194884  3.576645  0.021288   7.588427  5.201101  0.665869
24    CONN  6.820027  3.533319  0.029646   8.518219  5.046137  0.665606
25     CSU  8.281961  4.920814  0.020071   8.426358  5.184135  0.742448
26    DUKE  4.939863  3.869200  0.026820  10.183412  3.817306  0.550918
27     ECU  6.932342  3.211270  0.025221  10.970102  5.523292  0.767522
28     EMU  6.843331  3.514227  0.033939   6.411771  4.243821  0.817215
29     FAU  8.059321  5.664689  0.017093   6.951763  3.861498  0.711668
..     ...       ...       ...       ...        ...       ...       ...
100   UCLA  7.495055  3.850877  0.016960   7.352827  5.731864  1.056497
101    UGA  8.410620  5.816122  0.036325   5.696673  3.670149  0.893733
102     UK  6.196891  4.129230  0.018910   7.954322  4.580667  0.770897
103    ULL  6.029430  4.956831  0.033402   8.731278  4.954785  0.618112
104    ULM  7.728014  4.349340  0.022118   9.314356  5.562576  0.607721
105  UMASS  6.689593  3.954298  0.014853   6.979959  4.712347  0.748952
106    UMD  5.152152  3.906358  0.028892   6.711748  4.653558  1.050842
107    UNC  5.252366  3.538813  0.048205   7.419774  4.632013  1.123415
108   UNLV  6.456342  5.120316  0.032643   7.223199  5.246647  0.523886
109    UNM  5.094841  4.926609  0.072308   8.223237  4.785856  0.804661
110    UNT  6.847929  3.939014  0.028970   7.956335  4.675936  0.656976
111    USA  5.671625  2.808695  0.035609   8.204301  3.942987  0.806663
112    USC  7.992155  4.658695  0.027821   6.916926  4.224129  0.967823
113    USF  7.368281  5.195067  0.014353   6.700439  3.360069  1.093726
114    USM  6.799492  4.846235  0.016566   6.801191  3.649128  0.967244
115    USU  5.923361  4.425034  0.029242   6.292657  4.508425  0.830482
116   UTAH  6.672376  3.794104  0.029980   6.246345  3.822873  0.758452
117   UTEP  4.161782  3.082639  0.040719   7.731395  5.350421  0.925790
118   UTSA  5.721194  4.529440  0.020862   7.158606  3.823913  0.834540
119    UVA  5.707006  2.961152  0.022716   6.359535  4.509639  0.700914
120    VAN  6.659670  3.354048  0.022146   7.751382  4.670836  0.801186
121     VT  6.889339  3.823686  0.022246   7.840570  3.299535  0.571531
122   WAKE  7.773125  4.347685  0.014773   6.679597  4.216667  0.592371
123   WASH  7.399711  4.737057  0.017750   6.045771  2.562783  0.539401
124    WIS  7.637204  4.850720  0.050793   5.777253  3.102007  0.748494
125    WKU  6.357368  1.775323  0.018806   6.855947  4.537496  0.718557
126    WMU  5.562987  4.405003  0.027640   7.303664  4.330881  0.677358
127    WSU  5.776408  2.436454  0.028801   6.846048  4.209150  0.682879
128    WVU  7.813716  3.847344  0.028013   8.033600  5.056936  0.844533
129    WYO  5.381190  3.249128  0.021264   6.937551  3.363671  0.661525

[130 rows x 7 columns]

In [12]:
prod_df.to_csv('Data/2017_season_efficiencies.csv', index=False)